[project]
name = "sms-spoofer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "annotated-types==0.7.0",
    "certifi==2026.5.20",
    "cffi==2.0.0",
    "charset-normalizer==3.4.7",
    "cryptography==48.0.1",
    "idna==3.18",
    "pycparser==3.0",
    "pydantic==2.13.4",
    "pydantic-core==2.46.4",
    "pyjwt==2.13.0",
    "requests==2.34.2",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.2",
    "urllib3==2.7.0",
    "vonage==4.8.1",
    "vonage-account==1.1.2",
    "vonage-application==2.0.2",
    "vonage-http-client==1.5.2",
    "vonage-identity-insights==1.0.0",
    "vonage-jwt==1.1.5",
    "vonage-messages==1.7.1",
    "vonage-network-auth==1.0.2",
    "vonage-network-number-verification==1.0.2",
    "vonage-network-sim-swap==1.1.2",
    "vonage-number-insight==1.0.7",
    "vonage-numbers==1.0.5",
    "vonage-sms==1.2.0",
    "vonage-subaccounts==1.0.4",
    "vonage-users==1.2.2",
    "vonage-utils==1.1.4",
    "vonage-verify==2.2.0",
    "vonage-verify-legacy==1.1.0",
    "vonage-video==1.5.1",
    "vonage-voice==1.5.0",
]
